homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: !secret time_zone
  customize: !include customize.yaml

http:
  base_url: !secret http_baseurl
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: True
  login_attempts_threshold: 2

config:

conversation:

discovery:

frontend:

history:

logbook:

recorder:
  purge_days: 5

sun:

updater:

automation: !include_dir_merge_list automation/

group: !include_dir_merge_named group/

scene: !include scene.yaml

sensor: !include sensor.yaml

zone: !include zone.yaml

cover:
  - platform: myq
    username: !secret cover_username
    password: !secret cover_password
    type: liftmaster

device_tracker:
  - platform: bluetooth_tracker
    track_new_devices: no
  - platform: nmap_tracker
    hosts: 192.168.86.1/24
    home_interval: 10
    consider_home: 180
    track_new_devices: no

ecobee:
  api_key: !secret ecobee_key
  hold_temp: False

hdmi_cec:
  devices:
    0: Television
    2: Nvidia Shield
    3: Raspberry Pi

ifttt:
  key: !secret ifttt_key

notify:
  - platform: joaoapps_join
    device_id: group.android
    name: join
    api_key: !secret join_apikey
  - platform: telegram
    name: TacoBot
    api_key: !secret telegram_API
    chat_id: !secret telegram_group_ID

telegram_webhooks:
  api_key: !secret telegram_API
  user_id:
    jake: !secret telegram_ID_jake
    abbey: !secret telegram_ID_abbey

zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 10000 # Polling speed in miliseconds
  config_path: /srv/homeassistant/lib/python3.4/site-packages/libopenzwave-0.3.2-py3.4-linux-armv7l.egg/config
