  ##############
 #  Presence  #
##############
- alias: Abbey is home
  trigger:
    platform: state
    entity_id: group.abbey
    state: 'home'
  #condition:
  #  condition: time
  #  after: '05:00:00'
  #  before: '06:00:00'
  action:
    service: notify.join
    data:
      message: "Abbey is Home"

- alias: Abbey is away
  trigger:
    platform: state
    entity_id: group.abbey
    state: 'not_home'
  #condition:
  #  condition: time
  #  after: '05:00:00'
  #  before: '06:00:00'
  action:
    service: notify.join
    data:
      message: "Abbey is Away"

  ##############
 #  Updates   #
##############
- alias: 'Update Available Notifications'
  trigger:
    platform: state
    entity_id: updater.updater
  action:
    - service: notify.TacoBot
      data:
        message: "A new update for Home Assistant is available."
    - service: persistent_notification.create
      data:
        title:   "New Update"
        message: "A new update for Home Assistant is available."

  ##############
 #  Network  #
#############
- alias: Z-Wave network is complete
  trigger:
    platform: event
    event_type: zwave.network_ready
  action:
    service: notify.TacoBot
    data:
      message: "Z-Wave Network is up"

 ##############
 #  Battery  #
#############
- alias: Front door battery
  trigger:
    platform: numeric_state
    entity_id: sensor.frontdoor_battery
    below: 10
  action:
    service: notify.TacoBot
    data:
      message: "The front door battery is at {{ states.sensor.frontdoor_battery.state }}%"

- alias: Basement door battery
  trigger:
    platform: numeric_state
    entity_id: sensor.basement_door
    below: 10
  action:
    service: notify.TacoBot
    data:
      message: "The basment door battery is at {{ states.sensor.frontdoor_battery.state }}%"

- alias: Garage motion sensor battery
  trigger:
    platform: numeric_state
    entity_id: sensor.garage_motion_battery
    below: 10
  action:
    service: notify.TacoBot
    data:
      message: "The garage motion sensor battery is at {{ states.sensor.stairs_motion_battery.state }}%"

- alias: Garage door battery
  trigger:
    platform: numeric_state
    entity_id: sensor.garage_door_sensor
    below: 10
  action:
    service: notify.TacoBot
    data:
      message: "The garage door battery is at {{ states.sensor.frontdoor_battery.state }}%"
